model_type: Filterbank
loss_type: L1
stft_params: null
train_folder: 'data/musdb18hq/train'
valid_folder: 'data/musdb18hq/validation'
test_folder: 'data/musdb18hq/test'
train_generator_params:
  num_mixtures: 1000000
  coherent_prob: 1.0
valid_generator_params:
  num_mixtures: 10
  coherent_prob: 1.0
batch_size: 10
model_params:
  num_features: 128
  num_audio_channels: 1
  hidden_size: 64
  num_layers: 2
  bidirectional: True
  dropout: 0.2
  num_sources: 4
  activation: ['sigmoid','unit_norm']
  window_type: 'sqrt_hann'
  num_filters: 128
  hop_length: 32
optimizer_params:
  lr: 0.01
train_params:
  epoch_length: 10
  max_epochs: 20
save_name: 'filterbank_default'