model_type: UNet
stft_params: 
  window_length: 2047
  hop_length: 512
  window_type: sqrt_hann
train_folder: 'data/musdb18hq/train'
valid_folder: 'data/musdb18hq/validation'
test_folder: 'data/musdb18hq/test'
train_generator_params:
  num_mixtures: 1000000
  coherent_prob: 1.0
valid_generator_params:
  num_mixtures: 10
  coherent_prob: 1.0
batch_size: 10
model_params:
  in_channels: 1
  out_channels: 1
  init_features: 8
optimizer_params:
  lr: 0.001
train_params:
  epoch_length: 25
  max_epochs: 25
save_name: 'ST_unet_8f'