batch_size: 10
loss_type: L1
model_params:
  activation:
  - sigmoid
  - unit_norm
  bidirectional: true
  dropout: 0
  hidden_size: 64
  num_audio_channels: 1
  num_layers: 2
  num_sources: 4
model_type: Mask
optimizer_params:
  lr: 0.001
save_name: mask_default
stft_params:
  hop_length: 32
  window_length: 128
  window_type: sqrt_hann
test_folder: data/musdb18hq/test
train_folder: data/musdb18hq/train
train_generator_params:
  coherent_prob: 1.0
  num_mixtures: 1000000
train_params:
  epoch_length: 10
  max_epochs: 10
valid_folder: data/musdb18hq/validation
valid_generator_params:
  coherent_prob: 1.0
  num_mixtures: 10
